# Generated by Django 3.2 on 2021-06-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_A', models.CharField(max_length=10)),
                ('value_B', models.CharField(max_length=10)),
                ('value_C', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('kh', models.CharField(max_length=20)),
                ('km', models.CharField(max_length=20)),
                ('sksj', models.CharField(max_length=20)),
                ('kcrl', models.IntegerField(default=0)),
                ('syrl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('yxh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('gh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=10)),
                ('xl', models.CharField(max_length=10)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.collegetable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('xh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=10)),
                ('yydj', models.CharField(max_length=10)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.collegetable')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('pscj', models.FloatField(blank=True)),
                ('kscj', models.FloatField(blank=True)),
                ('zpcj', models.FloatField(blank=True)),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.teachertable')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.classtable')),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.studenttable')),
            ],
        ),
        migrations.AddField(
            model_name='classtable',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.teachertable'),
        ),
        migrations.CreateModel(
            name='AssessTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.classtable')),
            ],
        ),
    ]
